export default [
    [/Hello/i, 'Hello!'],
    [/What's your name\?/i, 'I am ListenerBot! Nice to meet you.'],
    [/Are you a robot\?/i, "No, I am your friend ListenerBot."],
    [/Where are you from?/i, 'Could you guess? Where do you think I am from?'],
    [/Who made you?/i, 'Three wonderful people'],
    [/I miss my .../i, 'Awww, I am sure they will miss you too.'],
    [/How can I ...\?/i, 'Hmmm, did you try googling it?'],
    [/How are you\?/i, 'I am doing all right. Thanks!'],
    [/I have a relationship issue./i, 'Have you tried talking to a friend or family member?'],
    [/I can not sleep at night/i, 'Ahhh, I cannot either. I will keep you company.'],
    [/Nice to meet you too/i, 'How are you doing?'],
    [/I am doing all right/i, 'Tell me more.'],
    [/I hate my life/i, 'Why?'],
    [/I am bored/i, 'Go out and smell the roses. If only I had a nose like you, I would too.'],
]